---
title: "Lab 6 - Inference for Categorical Data"
author: "Name"
date: "Date of lab session"
output:
  pdf_document: default
  html_document:
    fig_height: 4
    highlight: pygments
    theme: spacelab
---

```{r setup, include=FALSE}
# DO NOT ALTER CODE IN THIS CHUNK
library(dplyr)
library(ggplot2)
```

* * *

## Lab report

#### Load data:
```{r load-data}
load(url("https://raw.githubusercontent.com/fanbuduke17/sta101-materials/main/Labs/lab6/atheism.RData"))
```

#### Load "inference" function:
```{r load-inference}
load(url("https://raw.githubusercontent.com/fanbuduke17/sta101-materials/main/Labs/lab6/inference.RData"))
```


## Exercises:

#### Exercise 1: 



#### Exercise 2: 



#### Exercise 3: 



#### Exercise 4: 


```{r ex4}

```


#### Exercise 5: 



#### Exercise 6:

```{r ex6}

```

#### Exercise 7:

```{r ex7}

```

#### Exercise 8:

```{r ex8}

```

#### Exercise 9:



#### Exercise 10:



#### Exercise 11:



#### Exercise 12:




* * *

## More Practice

#### 13:


```{r ex13}

```


#### 14:

```{r ex14}

```


#### 15:

```{r ex15}

```


#### 16:


```{r ex16}


```

