---
title: "Lab 1 - Intro to R and RStudio"
author: "Team member 1, team member 2, team member 3"
date: "Date of lab session"
output:
  pdf_document: default
  html_document:
    highlight: pygments
    theme: spacelab
---

```{r setup, include=FALSE}
# DO NOT ALTER CODE IN THIS CHUNK
knitr::opts_chunk$set(echo = TRUE)
library(dplyr)
library(ggplot2)
```

* * *

## Lab report

**Load Arbuthnot data**
```{r}
load(url("https://raw.githubusercontent.com/fanbuduke17/sta101-materials/main/Labs/lab1/arbuthnot.RData"))
```

#### Exercise 1: 

```{r}
# code for Exercise 1 is already entered below as an example
arbuthnot$girls
```

#### Exercise 2:

[Enter your response for Exercise 2 here.]

```{r}
# enter your code for Exercise 2 here
```

#### Exercise 3:

```{r}
# enter your code for Exercise 3 here
```

* * *

### On your own:

**Load present day data**
```{r}
load(url("https://raw.githubusercontent.com/fanbuduke17/sta101-materials/main/Labs/lab1/present.RData"))
```

#### 4:



#### 5:



#### 6:



#### 7:


