---
title: "Lab 6 - Inference for numerical data"
author: "Team name"
date: "Date of lab session"
output:
  pdf_document: default
  html_document:
    fig_height: 4
    highlight: pygments
    theme: spacelab
---

```{r setup, include=FALSE}
# DO NOT ALTER CODE IN THIS CHUNK
library(dplyr)
library(ggplot2)
library(mosaic)
```

* * *

## Lab report

#### Load data:
```{r load-data}
load(url("https://raw.githubusercontent.com/fanbuduke17/sta101-materials/main/Labs/lab7/nc.RData"))
```

#### Load the `inference` function
```{r load-inference}
load(url("https://raw.githubusercontent.com/fanbuduke17/sta101-materials/main/Labs/lab6/inference.RData"))
```


#### Set a seed:
```{r set-seed}

```


## Exercises:

#### Exercise 1: 

```{r ex1}

```

#### Exercise 2: 


```{r ex2}

```


#### Exercise 3: 

```{r ex3}

```


#### Exercise 4: 


```{r ex4}

```


#### Exercise 5: 

```{r ex5}

```


* * *

## More Practice:

#### 6: 


```{r}

```


#### 7: 

```{r}

```


#### 8:

```{r}

```


#### 9:


```{r}


```


#### 10:

```{r}


```

